혁 레이싱 게임
Java-Bom/racing-game pull request #11
Opened 2020-03-19 16:48 UTC by nightmare73

짜고보니 테스트하기 매우 어려운 구조가 된거같습니다.
이 구조에서 테스트를 더 할 수 있게끔 하려면 코드를 어떤식으로 수정하면 좋을 지 생각이 잘 나지않아 답답합니다 ㅠㅠ 조언부탁드려요

2020-03-29 02:17 UTC, csbsjy commented
```java
package racing.domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class RacingFieldTest {

    @DisplayName("레이싱 결과가 범위 값 내에 있는 지 확인 및 턴, 차 수 확인")
    @Test
    void getRacingResult() {
        // given
        int totalTurns = 3;
        int carNumbers = 2;
        RacingField racingField = new RacingField(totalTurns, carNumbers, () -> 1);

        List<RacingTurn> racingSnapshot = racingField.race();

        // then
        assertThat(racingSnapshot.size()).isEqualTo(totalTurns);

        
        for (RacingTurn racingTurn : racingSnapshot) {
            List<Integer> racingResult = racingTurn.getRacingResult();
            assertThat(racingResult.size()).isEqualTo(carNumbers); // 이 테스트는 RaccingTurn 테스트에서 해야할 일
            racingResult.forEach(distance -> assertThat(distance).isEqualTo(totalTurns));
        }

        // 여기서 for문 쓰지 말라고 했던거 기억나는데.. 어떻게 하면 좋을지 모르겠습니다..
    }
}

// X - Y Problem
// X 를 테스트하렸는데 Y로 하고싶어. Y 몰라 그럼 Y 를 알려줘. X가 안되는 이유를 알아햐햐
```

2020-03-29 02:17 UTC, csbsjy commented
```java
package racing.domain;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class RacingField {
    private final int totalTurns;
    private final List<Car> cars; // 일급컬렉션을 권합니다. 차 생성 책임과 차에게 move를 할 수 있는 역할이 있는.

//    private List<RacingTurn> racingTurns;

    public RacingField(int totalTurns, int carNumbers, Mover mover) {
        this.totalTurns = totalTurns;
        this.cars = createCars(carNumbers, mover); // 생성자가 무거운 일을 해서 테스트가 힘들다. CarFactory를 만들어서 주입받는다면? 그리고 그 팩토리가 무버를 만든다면?
//        this.racingTurns = createRacingResult(); // 생성자에서 경기를 하고 있기 떄문에 테스트가 어려운 구조가 되었음.
    }

    //    public List<RacingTurn> getRacingTurns() {
//        return racingTurns;
//    }
// totalTurns 의 갯수만큼 RacingTurn 이 만들어지는지의 테스트 가능
    public List<RacingTurn> race() { // Naming race 로 바꾸는게 더 메시지에 적절한 것 같습니다.
        List<RacingTurn> racingTurns = new ArrayList<>();
        for (int turn = 0; turn < totalTurns; turn++) {
            racePerCar(); // race
            racingTurns.add(new RacingTurn(getCarDistances()));
        }
        return racingTurns;
    }

    private void racePerCar() { // race

        cars.forEach(Car::move); // for 가 더 성능좋음!
    }

    private List<Integer> getCarDistances() {
        return cars.stream()
                .map(Car::getDrivenDistance)
                .collect(Collectors.toList());
    }

    private List<Car> createCars(int carNumbers, Mover mover) {
        List<Car> cars = new ArrayList<>();
        // Mover mover = new CarMover(); // RacingField 가 Mover 생성의 책임을 가지고 있어야할까요? 인자로 받아도 좋을 것 같습니다
        for (int i = 0; i < carNumbers; i++) {
            Car car = new Car(mover);
            cars.add(car);
        }
        return cars;
    }
}
```

2020-03-29 02:18 UTC, csbsjy commented on src/main/java/racing/domain/CarMover.java
> +    private int getRandomIntUnder10() {
변수에 숫자를 넣지 않고 getRandomIntUnder(10) 이런식으로 인자를 받는식으로 바꾸는게 더 좋을 것 같습니다

2020-03-29 02:18 UTC, csbsjy commented on src/main/java/racing/domain/RacingField.java
> +        Mover mover = new CarMover();
RacingFiled 가 Mover 생성의 책임을 가지고 있는지 생각해봐야 하지 않을까용?

2020-03-31 16:42 UTC, pci2676 requested changes
> RacingField를 생성할 때는 Mover를 직접 생성해 줄 수없어, 랜덤값을 테스트할 수 없는 구조가 되었습니다.

이 부분에 대해 생각해 볼 수 있도록 리뷰를 남겨봤어
Mover의존성 제거에 대한 부분은 나는 지금 상태로도 충분한거 같아보여

리팩토링 다시한번 빡세게 해보자

2020-03-31 16:42 UTC, pci2676 commented on src/main/java/racing/domain/CarMover.java
> +    private int getRandomIntUnder10() {
Mover가 두가지 일을 하고 있는것 같아
1. 랜덤값을 구해 전진할 수 있는지의 여부를 구한다.
2. 전진할 거리의 양을 알려준다.

나는 전진 할 거리의 양은 Mover가 굳이 가지고 있지 않아도 된다고 생각해
Mover는 단순히 전진할수 있는지 없는지 정도의 역할만 가져가면 되지 않을까?

2020-03-31 16:42 UTC, pci2676 commented on src/main/java/racing/domain/CarMover.java
> +    private boolean isGoForward(int randomNum) {
is 라는 네이밍 보다는 can이라는 네이밍이 더 나은것 같아.
[참고](https://wiki.eclipse.org/Recommenders/CodingConventions)자료

2020-03-31 16:42 UTC, pci2676 commented on src/test/java/racing/domain/RacingFieldTest.java
> +        }
개인적으로 `isBetween()`메서드는 오히려 테스트를 잘못하게 하는 유혹에 빠뜨린다고 생각해

이러한 테스트가 나오게된것은 결국 구조의 문제가 있다라고 보게되는것 같아
`RacingField`에서 `Car`를 생성자 내부에서 만들기 때문에 `Car`의 제어를 개발자가 할수 없게 되는거잖아?
그렇다면 `Car`의 생성 부분을 외부로 도출해보는건 어떨까?

이름만 봐도 `RacingField`가 차를 만드는 책임을 가지고 있을거라 생각하기는 쉽지 않다고 생각해

2020-03-31 16:42 UTC, pci2676 commented on src/main/java/racing/domain/RacingField.java
> +    }
생성자 내부에서 너무 많은일을 하고있어
이러면 테스트 하기가 힘들거나 불가능한 구조가 되더라

2020-03-31 16:42 UTC, pci2676 commented on src/main/java/racing/domain/RacingField.java
> +        cars.forEach(Car::move);
[이거 한번 읽어보면 좋을듯!](https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/)

2020-03-31 16:42 UTC, pci2676 commented on src/main/java/racing/domain/RacingField.java
> +    }
생성자에서 말햇듯 굳이 모든걸 멤버변수로 들고있지말고
`.race()`와 같은 메서드에서 해당 결과를 연산해서 내보내줘도 어색하지 않을것 같아
인스턴스 변수가 많아지는 것은 되도록 지양하는게 좋은거 같아

2020-03-31 16:42 UTC, pci2676 commented on src/main/java/racing/domain/RacingTurn.java
> +public class RacingTurn {
일급 컬렉션 👍

2020-03-31 16:42 UTC, pci2676 commented on src/main/java/racing/domain/RacingTurn.java
> +        return racingResult;
racingResult를 그대로 외부에 노출시키게 될 경우
racingResult를 사용하는 쪽에서 `add`, `remove`, `clear`와 같은 메서드를 사용하면
어떤 일이 발생할 수 있을까?

2020-03-31 16:42 UTC, pci2676 commented on src/test/java/racing/domain/CarTest.java
> +        Car car = new Car(() -> CarMover.GO_FORWARD);
```suggestion
        // given
        Car car = new Car(() -> CarMover.GO_FORWARD);
        
        // when
```

given 절에 해당하는게 맞는것 같아보여

2020-03-31 16:42 UTC, pci2676 commented on src/test/java/racing/domain/RacingFieldTest.java
> +    @DisplayName("레이싱 결과가 범위 값 내에 있는 지 확인 및 턴, 차 수 확인")
> 범위 값 내에 있는 지 확인 및 턴, 차 수 확인

테스트 설명에서 적혀있듯이
1. 범위 값 내에 있는지 확인
2. 턴 수 확인
3. 차 수 확인

3가지 테스트 항목을 한가지 테스트에서 하고 있는것 같아
테스트를 분리 해보는건 어떨까?

2020-04-02 08:44 UTC, nightmare73 commented on src/main/java/racing/domain/CarMover.java
> +    private boolean isGoForward(int randomNum) {
나중에 뒤로 가거나 n칸 을 갈수도 있다던가 그런 변수들이 생길수도 있을거란 생각에
Mover가 전진할 거리의 양을 알려주고 있던 거였어. 만일 더 많은 경우의 거리의 양이 생긴다면
(예를 들면 랜덤수가 0~2가 나오면 -1칸 // 3~5면 0 칸 // 10이면 2칸 // 나머지 1칸) 오히려 다른 구조가 나오려나 ?

2020-04-02 08:47 UTC, nightmare73 commented on src/main/java/racing/domain/RacingField.java
> +    }
이게 .race() 를 한 번 호출하면 원하는 값이 나오지만, 두 번째 호출부터는
각 Car에 distance들이 남아있는 상태에서 또 한 번 움직이는거라 누적된 값을 가진 List<RacingTurn> 객체가 튀어나온단말이지...? 그거를 막기위해서 필드로 두었던 거였어.

2020-04-02 08:49 UTC, nightmare73 commented on src/main/java/racing/domain/RacingTurn.java
> +        return racingResult;
음... 자바에서는 List에 add remove clear 등이 다 있구나
코틀린에서는 아예 List (InterFace) 는 쓰기관련된 메소드가 존재하지않아서 List<>로 리턴하게 되면 아예 ReadOnly로만 사용가능했어. 코틀린에서는 Java Collection을 쓰는게 아니라 Kotlin Collection을 따로 쓰나보네.
이것은 return new ArrayList(racingResult); 로 해결될 수 있다고 봐

2020-04-02 08:51 UTC, nightmare73 commented on src/main/java/racing/domain/CarMover.java
> +    private int getRandomIntUnder10() {
@csbsjy  오... 생각치못했는데 감사합니당

2020-04-23 17:17 UTC, pci2676 requested changes
ㅎㅎ 조금만더 수정해 봅시다!

2020-04-23 17:17 UTC, pci2676 commented on src/main/java/racing/domain/RacingResult.java
> +    }
`List<RacingTurn> racingTurns` 를 관리하는 일급 컬렉션을 사용해 보는건 어떨까?

2020-04-23 17:17 UTC, pci2676 commented on src/main/java/racing/view/InputHelper.java
> +    }
입력이 `a,,b` 와 같이 입력된 경우는 올바르게 입력되는 걸까?
그렇다면 그러한 검증은 누가 해주어야 하는걸까?
어떠한 객체가 있으면 좋을지 생각해보면 좋을 것 같아.

2020-04-23 17:17 UTC, pci2676 commented on src/test/java/racing/domain/CarFactoryTest.java
> +        assertThat(racingCars).isEqualTo(expectedRacingCars);
오잉 이거 통과해?
설정한 양이 2개이고 add한거는 3개인데??

2020-04-23 17:17 UTC, pci2676 commented on src/test/java/racing/domain/CarFactoryTest.java
> +        assertThat(racingCars).isEqualTo(expectedRacingCars);
엥 이거 요구사항, 실제코드랑 다른 테스트 코드 같은데?

2020-04-23 17:17 UTC, pci2676 commented on src/test/java/racing/domain/RacingCarsTest.java
> +        assertThat(racingCars.getDistances()).isEqualTo(Arrays.asList(1));
```suggestion
        // given
        Car car = new Car(() -> true);
        RacingCars racingCars = new RacingCars(Arrays.asList(car));

        // when
        racingCars.move();

        // then
        assertThat(car.getDrivenDistance()).isEqualTo(1);
```

나라면 이렇게 했을 것 같아! 이건 어떻게 생각해?

2020-04-23 17:17 UTC, pci2676 commented on src/test/java/racing/domain/RacingFieldTest.java
> +        List<RacingTurn> expectedRacingTurns = Arrays.asList(racingTurn);
`given`절이 많아질수록 테스트 하기 불편하다고 느꼈을 것 같은데
줄이고도 테스트가 가능하도록 바꿀 수 없을까?

2020-04-24 07:46 UTC, nightmare73 commented on src/main/java/racing/view/InputHelper.java
> +    }
아... 입력값에 대해 예외케이스를 아예 생각을 안하고 짰네...
이런걸 좀 생각하면서 짜야되는데 자꾸 이런 케이스들에 대해 생각을 잘 못하는거같아

2020-04-24 07:46 UTC, nightmare73 commented on src/test/java/racing/domain/CarFactoryTest.java
> +        assertThat(racingCars).isEqualTo(expectedRacingCars);
아 제가 테스트코드를 아예 건들질 않았습니다.... 지송합니다 테스트코드도 수정하겠씁니다

2020-04-24 07:47 UTC, nightmare73 commented on src/test/java/racing/domain/RacingCarsTest.java
> +        assertThat(racingCars.getDistances()).isEqualTo(Arrays.asList(1));
아 저게 더 깔끔해보이네요
먼가 변수 하나하나 다 설명해주려고 저리 한것도있는데, 한줄로 하는게 더 낫네요

2020-04-24 07:47 UTC, nightmare73 commented on src/test/java/racing/domain/RacingFieldTest.java
> +        List<RacingTurn> expectedRacingTurns = Arrays.asList(racingTurn);
음... 잘 몰르겠지만 생각해볼게여

2020-04-29 14:44 UTC, nightmare73 commented on src/main/java/racing/view/InputHelper.java
> +    }
이부분은 Car생성시 이름이 공백인 경우 Exception 터트리는걸로 작성했음

2020-04-29 14:44 UTC, nightmare73 commented on src/main/java/racing/view/InputHelper.java
> +    }
이부분은 Car생성시 이름이 공백인 경우 Exception 터트리는걸로 작성했음

2020-05-02 00:56 UTC, merged